clear all;
clc;

load('./zero_point_three_data/gpi_method.mat', 'Sigma', 'gpi_method_mmf_rate_list', 'gpi_method_time_list', 'snrdB_list');
load('./zero_point_three_data/low_complexity.mat', 'low_complexity_mmf_rate_list', 'low_complexity_time_list');
load('./zero_point_three_data/multicast_sca.mat', 'multicast_sca_mmf_rate_list', 'multicast_sca_time_list');
load('./zero_point_three_data/multicast_wmmse.mat', 'multicast_wmmse_mmf_rate_list', 'multicast_wmmse_time_list');
load('./zero_point_three_data/noma_sca.mat', 'noma_sca_mmf_rate_list', 'noma_sca_time_list');
load('./zero_point_three_data/noma_wmmse.mat', 'noma_wmmse_mmf_rate_list', 'noma_wmmse_time_list');
load('./zero_point_three_data/rsma_sca.mat', 'rsma_sca_mmf_rate_list', 'rsma_sca_time_list');
load('./zero_point_three_data/rsma_wmmse.mat', 'rsma_wmmse_mmf_rate_list', 'rsma_wmmse_time_list');
load('./zero_point_three_data/sdma_sca.mat', 'sdma_sca_mmf_rate_list', 'sdma_sca_time_list');
load('./zero_point_three_data/sdma_wmmse.mat', 'sdma_wmmse_mmf_rate_list', 'sdma_wmmse_time_list');

figure;
set(gcf, 'Position', [100 100 2400, 800]);
subplot('Position', [0.03, 0.22, 0.28, 0.7]);
hold on;
plot(snrdB_list, rsma_sca_mmf_rate_list, ...
    'Color', 'green', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'RSMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, rsma_wmmse_mmf_rate_list, ...
    'Color', 'green', ...
    'LineStyle', ':', ...
    'Marker', '^', ...
    'DisplayName', 'RSMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, noma_sca_mmf_rate_list, ...
    'Color', '#FF8C00', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'NOMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, noma_wmmse_mmf_rate_list, ...
    'Color', '#FF8C00', ...
    'LineStyle', ':', ...
    'Marker', '+', ...
    'DisplayName', 'NOMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, sdma_sca_mmf_rate_list, ...
    'Color', '#05B9E2', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'SDMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, sdma_wmmse_mmf_rate_list, ...
    'Color', '#05B9E2', ...
    'LineStyle', ':', ...
    'Marker', 'x', ...
    'DisplayName', 'SDMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, multicast_sca_mmf_rate_list, ...
    'Color', '#8983BF', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Multicast-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, multicast_wmmse_mmf_rate_list, ...
    'Color', '#8983BF', ...
    'LineStyle', ':', ...
    'Marker', 'square', ...
    'DisplayName', 'Multicast-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, gpi_method_mmf_rate_list, ...
    'Color', 'black', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'RSMA-GPI', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, low_complexity_mmf_rate_list, ...
    'Color', 'red', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Proposed Low Complexity Algorithm', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
xlabel('SNR [dB]', 'FontSize', 22);
ylabel('MMF Rate [bit/s/Hz]', 'FontSize', 22);
legend('FontSize', 22);
set(legend, 'Position', [0.45, 0.005, 0.1, 0.1], 'NumColumns', 6);
grid on;
box on;
set(gca, 'FontSize', 22);
title(strcat('(a){ }', '\sigma_1 = ', sprintf('%.1f,', Sigma(1)), '{ }', '\sigma_2 = ', sprintf('%.1f', Sigma(2))), 'FontName', 'Times New Roman', 'FontSize', 22);

subplot('Position', [0.71, 0.22, 0.28, 0.7]);
hold on;
plot(snrdB_list, log10(rsma_sca_time_list), ...
    'Color', 'green', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'RSMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, log10(rsma_wmmse_time_list), ...
    'Color', 'green', ...
    'LineStyle', ':', ...
    'Marker', '^', ...
    'DisplayName', 'RSMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, log10(noma_sca_time_list), ...
    'Color', '#FF8C00', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'NOMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, log10(noma_wmmse_time_list), ...
    'Color', '#FF8C00', ...
    'LineStyle', ':', ...
    'Marker', '+', ...
    'DisplayName', 'NOMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, log10(sdma_sca_time_list), ...
    'Color', '#05B9E2', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'SDMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, log10(sdma_wmmse_time_list), ...
    'Color', '#05B9E2', ...
    'LineStyle', ':', ...
    'Marker', 'x', ...
    'DisplayName', 'SDMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, log10(multicast_sca_time_list), ...
    'Color', '#8983BF', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Multicast-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, log10(multicast_wmmse_time_list), ...
    'Color', '#8983BF', ...
    'LineStyle', ':', ...
    'Marker', 'square', ...
    'DisplayName', 'Multicast-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, log10(gpi_method_time_list), ...
    'Color', 'black', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'GPI-MMF-RS', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, log10(low_complexity_time_list), ...
    'Color', 'red', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Proposed Low Complexity Algorithm', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
xlabel('SNR [dB]', 'FontSize', 22);
ylabel('CPU Time [s]', 'FontSize', 22);
%legend('FontSize', 13);
%set(legend, 'Location', 'SouthOutside', 'NumColumns', 6);
grid on;
box on;
ax = gca();
YTickLabel = {};
for item = ax.YTick
    str = sprintf('10^{%d}', item);
    YTickLabel = [YTickLabel, str];
end
ax.YTickLabel = YTickLabel;
ax.XTick = snrdB_list;
set(gca, 'FontSize', 22);
title(strcat('(c){ }', '\sigma_1 = ', sprintf('%.1f, ', Sigma(1)), '{ }', '\sigma_2 = ', sprintf('%.1f', Sigma(2))), 'FontName', 'Times New Roman', 'FontSize', 22);

clear *list Sigma;

load('./one_and_one_data/gpi_method.mat', 'K', 'Nt', 'Sigma', 'channel_num', 'gpi_method_mmf_rate_list', 'gpi_method_time_list', 'snrdB_list');
load('./one_and_one_data/low_complexity.mat', 'low_complexity_mmf_rate_list', 'low_complexity_time_list');
load('./one_and_one_data/multicast_sca.mat', 'multicast_sca_mmf_rate_list', 'multicast_sca_time_list');
load('./one_and_one_data/multicast_wmmse.mat', 'multicast_wmmse_mmf_rate_list', 'multicast_wmmse_time_list');
load('./one_and_one_data/noma_sca.mat', 'noma_sca_mmf_rate_list', 'noma_sca_time_list');
load('./one_and_one_data/noma_wmmse.mat', 'noma_wmmse_mmf_rate_list', 'noma_wmmse_time_list');
load('./one_and_one_data/rsma_sca.mat', 'rsma_sca_mmf_rate_list', 'rsma_sca_time_list');
load('./one_and_one_data/rsma_wmmse.mat', 'rsma_wmmse_mmf_rate_list', 'rsma_wmmse_time_list');
load('./one_and_one_data/sdma_sca.mat', 'sdma_sca_mmf_rate_list', 'sdma_sca_time_list');
load('./one_and_one_data/sdma_wmmse.mat', 'sdma_wmmse_mmf_rate_list', 'sdma_wmmse_time_list');

subplot('Position', [0.36, 0.22, 0.28, 0.7]);
hold on;
plot(snrdB_list, rsma_sca_mmf_rate_list, ...
    'Color', 'green', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'RSMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, rsma_wmmse_mmf_rate_list, ...
    'Color', 'green', ...
    'LineStyle', ':', ...
    'Marker', '^', ...
    'DisplayName', 'RSMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, noma_sca_mmf_rate_list, ...
    'Color', '#FF8C00', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'NOMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, noma_wmmse_mmf_rate_list, ...
    'Color', '#FF8C00', ...
    'LineStyle', ':', ...
    'Marker', '+', ...
    'DisplayName', 'NOMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, sdma_sca_mmf_rate_list, ...
    'Color', '#05B9E2', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'SDMA-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, sdma_wmmse_mmf_rate_list, ...
    'Color', '#05B9E2', ...
    'LineStyle', ':', ...
    'Marker', 'x', ...
    'DisplayName', 'SDMA-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, multicast_sca_mmf_rate_list, ...
    'Color', '#8983BF', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Multicast-SCA', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, multicast_wmmse_mmf_rate_list, ...
    'Color', '#8983BF', ...
    'LineStyle', ':', ...
    'Marker', 'square', ...
    'DisplayName', 'Multicast-WMMSE', ...
    'LineWidth', 4, ...
    'MarkerSize', 9);
plot(snrdB_list, gpi_method_mmf_rate_list, ...
    'Color', 'black', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'RSMA-GPI', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
plot(snrdB_list, low_complexity_mmf_rate_list, ...
    'Color', 'red', ...
    'LineStyle', '-', ...
    'Marker', "none", ...
    'DisplayName', 'Proposed Low Complexity Algorithm', ...
    'LineWidth', 2, ...
    'MarkerSize', 7);
xlabel('SNR [dB]', 'FontSize', 22);
ylabel('MMF Rate [bit/s/Hz]', 'FontSize', 22);
grid on;
box on;
set(gca, 'FontSize', 22);
title(strcat('(b){ }', '\sigma_1 = ', sprintf('%.1f, ', Sigma(1)), '{ }', '\sigma_2 = ', sprintf('%.1f', Sigma(2))), 'FontName', 'Times New Roman', 'FontSize', 22);
